### ISSUE TITLE
merge rosbag

### ISSUE THREAD

**Issue by HJMGARMIN** [eliabntt/GRADE_data#1]
Thank you for your great work.
I downloaded the dataset and I found that there are ten rosbags in each package. I want to know how to merge them into one rosbag.

**Comment by eliabntt** [comment]
Hi, 

You can either play them with `rosbag play *.bag --clock --other-options` this will play all the bags in the folder in the correct order. 

If you want to merge them you can use [this](https://pypi.org/project/rosbag-merge/) or write your own script to read the bags and write the data you need in a new one using the official [APIs](https://wiki.ros.org/rosbag/Code%20API).

**Comment by HJMGARMIN** [comment]
Thanks for your reply. It's useful.

**Comment by eliabntt** [comment]
No problem!

Also, note that the bags may be compressed (forgot to mention that in the readme).

you can decompress them before playing with
`rosbag decompress *.bag` This will automatically decompress all the bags in the folder.

**Comment by eliabntt** [comment]
That depends on your system. Probably, yes.
